config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'dogs/introduce1' => 'dogs#introduce1'
  get 'dogs/introduce2' => 'dogs#introduce2'
  get 'dogs/introduce3' => 'dogs#introduce3'
  get 'dogs/introduce4' => 'dogs#introduce4'
  get 'dogs/introduce5' => 'dogs#introduce5'
  get 'dogs/introduce6' => 'dogs#introduce6'
  get 'dogs/introduce7' => 'dogs#introduce7'
  get 'dogs/introduce8' => 'dogs#introduce8'
  get 'dogs/introduce9' => 'dogs#introduce9'
  get 'dogs/introduce10' => 'dogs#introduce10'
  get 'dogs/introduce11' => 'dogs#introduce11'
  get 'dogs/introduce12' => 'dogs#introduce12'

  get 'dogs/:dog_id/likes' => 'likes#create'
  get 'dogs/:dog_id/likes/:id' => 'likes#destroy'
  
  resources :users, only: [:show]


  resources :dogs do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]

  end


  get 'perfumes' => 'perfumes#index'
  get 'perfumes/question1' => 'perfumes#question1'
  get 'perfumes/question2' => 'perfumes#question2'
  get 'perfumes/question3' => 'perfumes#question3'
  get 'perfumes/question4' => 'perfumes#question4'
  get 'perfumes/show1' => 'perfumes#show1'
  get 'perfumes/show2' => 'perfumes#show2'
  get 'perfumes/show3' => 'perfumes#show3'
  get 'perfumes/show4' => 'perfumes#show4'
  get 'perfumes/show5' => 'perfumes#show5'
  get 'perfumes/show6' => 'perfumes#show6'
  
  get 'memes' => 'memes#index'
  get 'memes/question1' => 'memes#question1'
  get 'memes/question2' => 'memes#question2'
  get 'memes/question3' => 'memes#question3'
  get 'memes/question4' => 'memes#question4'
  get 'memes/show1' => 'memes#show1'
  get 'memes/show2' => 'memes#show2'
  get 'memes/show3' => 'memes#show3'
  get 'memes/show4' => 'memes#show4'
  get 'memes/show5' => 'memes#show5'
  get 'memes/show6' => 'memes#show6'

  root 'dogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :dog
end

app/models/dog.rb
class Dog < ApplicationRecord
    belongs_to :user  

    mount_uploader :image, ImageUploader
    has_many :comments, dependent: :destroy

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :dog
  belongs_to :user

  validates_uniqueness_of :dog_id, scope: :user_id

end

app/models/meme.rb
class Meme < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :dogs, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_dogs, through: :likes, source: :dog
  has_many :comments, dependent: :destroy
  
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  def already_liked?(dog)
    self.likes.exists?(dog_id: dog.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    def create
        dog = Dog.find(params[:dog_id])
        comment = dog.comments.build(comment_params) 
        comment.user_id = current_user.id
        if comment.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path) 
        else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path)
        end
    end
    
    private

    def comment_params
        params.require(:comment).permit(:content)
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def index
        @dogs = Dog.all
    end
    def new
        @dog = Dog.new
    end

    def create
        dog = Dog.new(dog_params)
        dog.user_id = current_user.id

        if dog.save!
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def show
        @dog = Dog.find(params[:id])
        @comments = @dog.comments
        @comment = Comment.new
    end
    
    def edit
      @dog = Dog.find(params[:id])
    end
    def update
      dog = Dog.find(params[:id])
      if dog.update(dog_params)
        redirect_to :action => "show", :id => dog.id
      else
        redirect_to :action => "new"
      end
    end

    def destroy
      dog = Dog.find(params[:id])
      dog.destroy
      redirect_to action: :index
    end

    def introduce1
    end

    def introduce2
    end

    def introduce3
    end

    def introduce4
    end

    def introduce5
    end

    def introduce6
    end

    def introduce7
    end

    def introduce8
    end

    def introduce9
    end

    def introduce10
    end

    def introduce11
    end

    def introduce12
    end

    private
    def dog_params
      params.require(:dog).permit(:name, :genre, :about, :user_id, :image, :youtube_url)
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(dog_id: params[:dog_id]) 
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(dog_id: params[:dog_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end

end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
    def index
    end

    def new
        @meme = Meme.new
    end

    def show
        @meme = Meme.find_by(id: params[:id])
    end

    def create
        meme = Meme.new(meme_params)
        if meme.save
            flash[:notice] = "診断が完了しました"
            redirect_to meme_path(meme.id)
        else
            redirect_to :action => "new"
        end
    end
  
  private
    def meme_params
        params.require(:meme).permit(:question1, :question2, :question3, :question4)
    end
end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController


    def question1
    end

    def question2
    end

    def question3
    end

    def question4
    end

    def show1
    end

    def show2
    end

    def show3
    end

    def show4
    end

    def show5
    end

    def show6
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
    def find_youtube_url(youtube_url)
        if youtube_url[0..16] == "https://youtu.be/"
          return youtube_url[17..27]
          # "https://youtu.be/WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
        else
          return youtube_url[32..42]
          # "https://www.youtube.com/watch?v=WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
        end
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dogs/cuties.html.erb
紹介ページ

app/views/dogs/edit.html.erb
<%= form_for @dog do |f| %>
    <%= f.label :犬の名前%>
    <%= f.text_field :name, :size => 140 %> 
    <%= f.label :ジャンル%>
    <%= f.text_field :genre, :size => 140 %> 
    <%= f.label :詳細%>
    <%= f.text_field :about, :size => 140 %> 
    <%= f.submit "編集する" %>
  
  <% end %>

app/views/dogs/index.html.erb
<div class = "dogs-index">
  <h1>きゃわなわんちゃん一覧</h1>

  <div class = "introduce">
    <div class = "introduce1">
      <div class = "introduce_image">
          <%= link_to image_tag("maruchi-zu.jpg", class:"introduce_image1"), dogs_introduce1_path %>
          <h3>マルチーズ</h3>
      </div>
      <div class = "introduce_image">
          <%= link_to image_tag("chiwawa.jpg", class:"introduce_image2"), dogs_introduce2_path %>
          <h3>チワワ</h3>
      </div>
      <div class = "introduce_image">
          <%= link_to image_tag("dakkusufunndo.jpg", class:"introduce_image3"), dogs_introduce3_path %>
          <h3>ミニチュア・ダックスフンド</h3>
      </div>
      <div class = "introduce_image">
          <%= link_to image_tag("pome.jpg", class:"introduce_image4"), dogs_introduce4_path %>
          <h3>ポメラニアン</h3>
      </div>
    </div>
    <div class = "introduce2">
      <div class = "introduce_image">
          <%= link_to image_tag("toypoodle.jpg", class:"introduce_image5"), dogs_introduce5_path %>
          <h3>トイ・プードル</h3>
      </div>
      <div class = "introduce_image">
          <%= link_to image_tag("shunauza.jpg", class:"introduce_image6"), dogs_introduce6_path %>
          <h3>ミニチュア・シュナウザー</h3>
      </div>
      <div class = "introduce_image">
          <%= link_to image_tag("yo-kushateria.jpg", class:"introduce_image7"), dogs_introduce7_path %>
          <h3>ヨークシャー・テリア</h3>
      </div>
      <div class = "introduce_image">
          <%= link_to image_tag("shibainu.jpg", class:"introduce_image8"), dogs_introduce8_path %>
          <h3>柴犬</h3>
      </div>
    </div>
    <div class = "introduce3">
      <div class = "introduce_image">
          <%= link_to image_tag("burudog.jpg", class:"introduce_image9"), dogs_introduce9_path %>
          <h3>ブルドッグ</h3>
      </div>
      <div class = "introduce_image">
        <%= link_to image_tag("ko-gi-.jpg", class:"introduce_image10"), dogs_introduce10_path %>
        <h3>コーギー</h3>
      </div>
      <div class = "introduce_image">
          <%= link_to image_tag("retoriba-.jpg", class:"introduce_image11"), dogs_introduce11_path %>
          <h3>ゴールデンレトリバー</h3>
      </div>
      <div class = "introduce_image">
          <%= link_to image_tag("bo-da-kori-.jpg", class:"introduce_image12"), dogs_introduce12_path %>
          <h3>ボーダーコリー</h3>
      </div>
    </div>
  </div>

  <div class="botton">

  </div>
  <div class="dogs-container">
    <% if user_signed_in? %>
      <%= link_to "マイページへ", user_path(current_user.id) %>
    <% end %>

    <h3>一覧ページ</h3>

    <% @dogs.each do |t| %>
      <div class="dog">
      
        <%= image_tag t.image_url, size: "250x200" if t.image? %>
        <%= t.name %>
        <%= t.genre %>
        <%= t.about %>
        


        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
              <%= link_to dog_like_path(id: t.id, dog_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% else %>
              <%= link_to dog_likes_path(id: t.id, dog_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>

        <%= link_to "詳細へ", dog_path(t.id) %>
        
      </div>
    <% end %>
  </div>
</div>

app/views/dogs/introduce1.html.erb
<div class = "maruchi-zu">
    <h1>人懐っこく陽気で、活発な性格のマルチーズ

    最古の愛玩犬とされている
    毛色は純白（ピュアホワイト）淡いアイボリーの色調
    淡い茶色（タン）やレモン色が部分的に入っているマルチーズもいる
    物分かりのよさと洞察力も備わっている
</div>

app/views/dogs/introduce2.html.erb
<div class = "chiwawa">
<h1>大きくてつぶらな瞳とアップルヘッドと呼ばれる丸い頭が特徴的な小型のチワワ
小さい身体にうるうるお目目の愛らしいお顔
誰でも守りたくなる外見だが、性格は意外と勇敢な一面を持っている
</div>

app/views/dogs/introduce3.html.erb
ミニチュアダックスフンドは、体長は体高の2倍の長さという短足胴長の体型で、垂れ耳で中くらいの長さのマズルを持つ小型犬

app/views/dogs/introduce4.html.erb
ポメラニアンは小さな頭に丸い大きな目、手足も小さく、しっぽは背中に向けて巻いており、独特の豪華な毛吹きが特徴

app/views/dogs/new.html.erb
<h1>kikuno</h1>
<h3>新規投稿ページ</h3>
<%= form_for @dog do |f| %>


  <div class="field">
    <%= f.label :犬の名前 %>
    <%= f.text_field :name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :写真 %>
    <%= f.file_field :image %>
  </div>


  <div class="field">
    <%= f.label :性別  %>
    <%= f.select :sex, 
    [["男の子", "男の子"], 
    ["女の子", "女の子"]], 
    include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :犬種  %>
    <%= f.text_area :genre, :size => 10 %>
  </div>



  <div class="field">
    <%= f.label :かあいいポイント  %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>

  <%= f.label :youtube_url %>
  <%= f.text_field :youtube_url, :size => 140 %>

  <%= f.submit "投稿する" %>

<% end %>

app/views/dogs/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="dog">
  <p><%= @dog.name %></p>
  <p><%= @dog.created_at %></p>
  <% if user_signed_in? %>
  <% if current_user.already_liked?(@dog) %>
    <%= link_to dog_like_path(@dog), method: :delete do %>
      <i class="fas fa-heart"></i><%= @dog.likes.count %>
    <% end %>
  <% else %>
    <%= link_to dog_likes_path(@dog), method: :post do %>
      <i class="far fa-heart"></i><%= @dog.likes.count %>
      <% end %>
      <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= @dog.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_dog_path(@dog.id) %>
  <%= button_to "削除", dog_path(@dog.id), method: :delete %>
</div>
<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@dog, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i>
      <% end %>
    <% end %>
  <% end %>
</div>



<h2>いいねしたユーザー</h2>
<% @dog.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<%= link_to "Tweet一覧に戻る", dogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kikuno</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/5e45e79ec2.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hachi+Maru+Pop&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to "SUPER CUTIEなDOGS", dogs_path %></h1>
      <div class="header-list">
        <ul>
          <% if user_signed_in? %>
            <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "新規登録", new_user_registration_path %></li>
            <li><%= link_to "ログイン", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
      
      <%= link_to "新規投稿へ", new_dog_path %>
      <%= link_to "自分好みのミックス作れちゃうよ診断", perfumes_path %>
      <%= link_to "今の気分のワンチャンを紹介しちゃうよ診断", memes_path %>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <p>Copyright © GeekSalon All Rights Reserved.</p>
    </footer>
  </body>
</html>

app/views/memes/index.html.erb
<h1>わんわん診断スタート</h1>
<%= link_to "診断を始める", memes_question1_path, class: "link" %>

app/views/memes/new.html.erb
<%= form_for(@meme, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="meme-container">
        <div class="col-12">
            <p>Q1. どちらかと言うと…</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question1, "1", id: "custom_id1" %>
            <label for="custom_id1">大型犬がすき</label>
            <%= f.radio_button :question1, "2", id: "custom_id2" %>
            <label for="custom_id2">小型犬がすき</label>
        </div>
        <div class="col-12">
            <p>Q2. 毛並みは…</p>
        </div> 
        <div class="col-6">
            <%= f.radio_button :question2, "1", id: "custom_id3" %>
            <label for="custom_id3">ふわふわがいい！</label>
            <%= f.radio_button :question2, "2", id: "custom_id4" %>
            <label for="custom_id4">ストレートサラサラ～</label>
        </div>   
        <div class="col-12">
            <p>Q3. 人と接するときは…</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question3, "1", id: "custom_id5" %>
            <label for="custom_id5">相手の話をよく聞く方だ</label>
            <%= f.radio_button :question3, "2", id: "custom_id6" %>
            <label for="custom_id6">自分の話をよくする方だ</label>
        </div>
    
        <div class="col-12">
            <p>Q4. 大切にしたいのは…</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question4, "1", id: "custom_id7" %>
            <label for="custom_id7">論理性だ</label>
            <%= f.radio_button :question4, "2", id: "custom_id8" %>
            <label for="custom_id8">情緒だ</label>
        </div>
    </div>
    <div class="sindanbotan">
        <%= f.submit " 結果 " %>
    </div>
<% end %>

app/views/memes/question1.html.erb
<div class = "question1">
    <h1>第1問</h1>
    <h2>今の気分は、、、？</h2>
    <div class = "question1_1">
        <div class = "question1_image1_1">
            <%= link_to image_tag("happy.jpg", class:"question1_image1"), memes_question2_path %>
            <h3>ハッピー！</h3>
        </div>
        <div class = "question1_image2_1">
            <%= link_to image_tag("jinseiha-domo-do.jpg", class:"question1_image2"), memes_question3_path %>
            <h3>人生ハードモード</h3>
        </div>
        <div class = "question1_image3_1">
            <%= link_to image_tag("iraira.jpg", class:"question1_image3"), memes_question4_path %>
            <h3>むかつくううう</h3>
        </div>
    </div>

</div>

app/views/memes/question2.html.erb
<div class = "question2">
    <h1>第2問</h1>
    <h2>ハッピーな気分な時には、、、？</h2>
    <div class = "question2_1">
        <div class = "question2_image1_1">
            <%= link_to image_tag("kisuma.jpg", class:"question2_image1"), memes_show1_path %>
            <h3>ただただかわいい犬を拝みたい</h3>
        </div>
        <div class = "question2_image2_1">
            <%= link_to image_tag("kandou.jpg", class:"question2_image2"), memes_show2_path %>
            <h3>感動系もどんと来い！</h3>
        </div>
    </div>

</div>

app/views/memes/question3.html.erb
<div class = "question3">
    <h1>第2問</h1>
    <h2>人生ハードで、、、？</h2>
    <div class = "question3_1">
        <div class = "question3_image1_1">
            <%= link_to image_tag("genki.jpg", class:"question3_image1"), memes_show3_path %>
            <h3>元気出させてほしい</h3>
        </div>
        <div class = "question3_image2_1">
            <%= link_to image_tag("kusu.jpg", class:"question3_image2"), memes_show4_path %>
            <h3>クスッと笑わせてほしい</h3>
        </div>
    </div>

</div>

app/views/memes/question4.html.erb
<div class = "question4">
    <h1>第2問</h1>
    <h2>ストレスに感じてて、、、</h2>
    <div class = "question4_1">
        <div class = "question4_image1_1">
            <%= link_to image_tag("chill.jpg", class:"question4_image1"), memes_show5_path %>
            <h3>心を落ち着かせたい</h3>
        </div>
        <div class = "question4_image2_1">
            <%= link_to image_tag("iyashi.jpg", class:"question4_image2"), memes_show6_path %>
            <h3>癒しが欲しい</h3>
        </div>
    </div>

</div>

app/views/memes/show.html.erb
<div class="intoro">
  <h5>診断結果</h5>
  <p>あなたにおすすめの香りは…</p>
</div>
<div class="meme-container">
  <% case [@meme.question1, @meme.question2, @meme.question3, @meme.question4] %>
  <% when ["1", "1", "1", "1"] %>
    <h6>レモン</h6>
    <p>柑橘系の代表的な原料</p>
    <p>清涼感があり、爽やかな印象</p>
  <% when ["1", "1", "1", "2"] %>
    <h6>シトラス</h6>
    <p>オレンジに似た柑橘系の果物</p>
    <p>リラックス効果がある</p>
  <% when ["1", "1", "2", "1"] %>
    <h6>ローズ</h6>
    <p>華やかで上品な香り</p>
    <p>ストレスを緩和してくれる効果がある</p>
  <% when ["1", "1", "2", "2"] %>
    <h6>ラベンダー</h6>
    <p>優しく女性らしい香り</p>
    <p>気持ちを落ち着かせてくれる</p>
  <% when ["1", "2", "1", "1"] %>
    <h6>ジャスミン</h6>
    <p>爽やかなのに官能的な香り</p>
    <p>幸福感を得やすい</p>
  <% when ["1", "2", "1", "2"] %>
    <h6>ピーチ</h6>
    <p>フレッシュで優しい香り</p>
    <p>アンチエイジングにも最適</p>
  <% when ["1", "2", "2", "1"] %>
    <h6>アップル</h6>
    <p>特徴的で甘い香り</p>
    <p>万人受けしやすい</p>
  <% when ["1", "2", "2", "2"] %>
    <h6>ユーカリ</h6>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>
  <% when ["2", "1", "1", "1"] %>
    <h6>ローズマリー</h6>
    <p>きりりとした強めの香りが特徴的</p>
    <p>美容効果が高い</p>
  <% when ["2", "1", "1", "2"] %>
    <h6>ベルガモット</h6>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>
  <% when ["2", "1", "2", "1"] %>
    <h6>ムスク</h6>
    <p>雄のジャコウジカの腹部にある香嚢から抽出した香料</p>
    <p>官能的で重い香り</p>
  <% when ["2", "1", "2", "2"] %>
    <h6>アンバー</h6>
    <p>マッコウクジラの結石から抽出した香料</p>
    <p>魅惑的で色気のある香り</p>
  <% when ["2", "2", "1", "1"] %>
    <h6>シナモン</h6>
    <p>甘いスパイスの香り</p>
    <p>香水のアクセントとしてよく使われる</p>
  <% when ["2", "2", "1", "2"] %>
    <h6>バニラ</h6>
    <p>甘くて官能的な香り</p>
    <p>上品で年齢を問わず人気が高い</p>
  <% when ["2", "2", "2", "1"] %>
    <h6>イランイラン</h6>
    <p>色気のある濃厚で甘い香り</p>
    <p>恋愛に効果があり</p>
  <% when ["2", "2", "2", "2"] %>
    <h6>サンダルウッド</h6>
    <p>お香としてよく使われる白檀の香り</p>
    <p>集中力を高める効果もあり</p>
  <% end %>
</div>

app/views/perfumes/index.html.erb
<h1>診断機能 スタートページ</h1>

<%= link_to "自分好みのミックスつくれちゃうよ診断スタート☆彡", perfumes_question1_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>my page</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.dogs.each do |t| %>
  <%= t.name %>
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
  <%= t.genre %>
  <%= t.about %>
<% end %>

<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_dogs.each do |t| %>
  <%= t.name %>
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
  <%= t.genre %>
  <%= t.about %>
<% end %>
<!-- ここまで-->

<%= link_to "一覧に戻る", dogs_path %>